version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      solana:
        patterns:
          - "solana-*"
          - "agave-*"
          - "spl-*"
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      all-actions:
        patterns:
          - "*"
