[workspace]
members = [
    "bencher",
    "harness",
    "test-programs/cpi-target",
    "test-programs/primary",
]
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/mollusk"
readme = "README.md"
license = "MIT"
edition = "2021"
version = "0.0.4"

[workspace.dependencies]
bincode = "1.3.3"
mollusk-svm = { path = "harness", version = "0.0.4" }
mollusk-svm-bencher = { path = "bencher", version = "0.0.4" }
num-format = "0.4.4"
serde_json = "1.0.117"
solana-bpf-loader-program = "2.0"
solana-compute-budget = "2.0"
solana-logger = "2.0"
solana-program = "2.0"
solana-program-runtime = "2.0"
solana-system-program = "2.0"
solana-sdk = "2.0"
thiserror = "1.0.64"
