[workspace]
members = [
    "bencher",
    "harness",
    "test-programs/cpi-target",
    "test-programs/primary",
]
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/mollusk"
license = "../license"
edition = "2021"

[workspace.dependencies]
bincode = "1.3.3"
num-format = "0.4.4"
serde_json = "1.0.117"
solana-bpf-loader-program = "2.0"
solana-compute-budget = "2.0"
solana-logger = "2.0"
solana-program = "2.0"
solana-program-runtime = "2.0"
solana-system-program = "2.0"
solana-sdk = "2.0"
