[workspace]
members = [
    "bencher",
    "error",
    "fuzz/*",
    "harness",
    "keys",
    "programs/*",
    "test-programs/*",
]
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/mollusk"
readme = "README.md"
license = "MIT"
edition = "2021"
version = "0.0.10"

[workspace.dependencies]
bincode = "1.3.3"
bs58 = "0.5.1"
criterion = "0.5.1"
mollusk-svm = { path = "harness", version = "0.0.10" }
mollusk-svm-bencher = { path = "bencher", version = "0.0.10" }
mollusk-svm-error = { path = "error", version = "0.0.10" }
mollusk-svm-fuzz-fixture = { path = "fuzz/fixture", version = "0.0.10" }
mollusk-svm-fuzz-fixture-firedancer = { path = "fuzz/fixture-fd", version = "0.0.10" }
mollusk-svm-fuzz-fs = { path = "fuzz/fs", version = "0.0.10" }
mollusk-svm-keys = { path = "keys", version = "0.0.10" }
mollusk-svm-programs-memo = { path = "programs/memo", version = "0.0.10" }
mollusk-svm-programs-token = { path = "programs/token", version = "0.0.10" }
num-format = "0.4.4"
prost = "0.10"
prost-build = "0.10"
prost-types = "0.10"
serde = "1.0.203"
serde_json = "1.0.117"
serial_test = "2.0"
solana-bpf-loader-program = "=2.1.0"
solana-compute-budget = "=2.1.0"
solana-logger = "2.1"
solana-program = "2.1"
solana-program-runtime = "=2.1.0"
solana-system-program = "=2.1.0"
solana-sdk = "2.1"
solana-timings = "=2.1.0"
thiserror = "1.0.64"
