[workspace]
members = [
    "bencher",
    "harness",
    "harness/fuzz",
    "test-programs/cpi-target",
    "test-programs/primary",
]
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/mollusk"
license = "../license"
edition = "2021"

[workspace.dependencies]
bincode = "1.3.3"
bs58 = "0.5.1"
num-format = "0.4.4"
prost = "0.10"
prost-build = "0.10"
prost-types = "0.10"
serde_json = "1.0.117"
solana-bpf-loader-program = "1.18.14"
solana-logger = "1.18.14"
solana-program = "1.18.14"
solana-program-runtime = "1.18.14"
solana-system-program = "1.18.14"
solana-sdk = "1.18.14"
thiserror = "1.0.57"
