[package]
name = "mollusk"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
solana-bpf-loader-program = { workspace = true }
solana-program-runtime = { workspace = true }
solana-system-program = { workspace = true }
solana-sdk = { workspace = true }
solana-logger = { workspace = true }


[[bench]]
name = "ips"
harness = false

[dev-dependencies]
criterion = "0.5.1"
