[package]
name = "mollusk-svm"
version = "0.0.1"
description = "SVM program test harness."
documentation = "https://docs.rs/mollusk-svm"
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
fuzz = ["dep:mollusk-svm-fuzz"]

[dependencies]
bincode = { workspace = true }
mollusk-svm-fuzz = { path = "./fuzz", optional = true }
solana-bpf-loader-program = { workspace = true }
solana-program-runtime = { workspace = true }
solana-system-program = { workspace = true }
solana-sdk = { workspace = true }
solana-logger = { workspace = true }

[[bench]]
name = "ips"
harness = false

[dev-dependencies]
criterion = "0.5.1"
