[package]
name = "mollusk-svm"
description = "SVM program test harness."
documentation = "https://docs.rs/mollusk-svm"
authors = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[features]
fuzz = ["dep:mollusk-svm-fuzz-fixture"]

[dependencies]
bincode = { workspace = true }
mollusk-svm-fuzz-fixture = { workspace = true, optional = true }
solana-bpf-loader-program = { workspace = true }
solana-compute-budget = { workspace = true }
solana-program-runtime = { workspace = true }
solana-system-program = { workspace = true }
solana-sdk = { workspace = true }
solana-logger = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "ips"
harness = false
