[package]
name = "mollusk-bencher"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
mollusk = { path = "../harness" }
num-format = { workspace = true }
serde_json = { workspace = true }
solana-sdk = { workspace = true }

[dev-dependencies]
solana-logger = { workspace = true }