name: Backport to solana-v2.0

on:
  push:
    branches: [main]

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      - name: Backport to v2.0
        uses: ./.github/actions/backport
        with:
          label: v2.0
          base_branch: solana-v2.0
